import type { Metadata } from "next";
import Image from "next/image";
import {
  Geist,
  Geist_Mono,
  Inter,
  Manrope,
  Anek_Bangla,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
const anekBangla = Anek_Bangla({
  variable: "--font-anek-bangla",
  subsets: ["bengali"],
});

export const metadata: Metadata = {
  title: "Mazaya",
  description: "Generated by Dexber Teams",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}
        ${manrope.variable}  ${anekBangla.variable} h-full antialiased`}
    >
      <body className="relative min-h-full flex flex-col bg-transparent">
        {/* Full-page fixed background */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none bg-[#0a0700]">
          <Image
            src="/home/hero.png"
            alt="Hero Background"
            fill
            priority
            className="object-cover"
          />
          {/* Lighter overlay */}
          <div className="absolute inset-0 bg-black/60" />
        </div>

        <Navbar></Navbar>
        <main className="relative z-0">{children}</main>
      </body>
    </html>
  );
}
